surveys:
  - survey_name: pre
    file: assets/surveys/pre_survey.csv
    format: qualtrics
    machine_header_row_index: 0
    question_text_row_index: 1
    data_start_row_index: 3
    participant_id_column: email
    participant_id_mapping:
      file: assets/surveys/participant_id_map.csv
      key_column: email
      value_column: assigned_participant_id
      normalize: lower
    participant_metadata_columns:
      notes: consent
    skip_columns:
      - StartDate
      - EndDate
      - Status
      - IPAddress
      - Progress
      - Duration (in seconds)
      - Finished
      - RecordedDate
      - ResponseId
      - RecipientLastName
      - RecipientFirstName
      - RecipientEmail
      - ExternalReference
      - LocationLatitude
      - LocationLongitude
      - DistributionChannel
      - UserLanguage
    include_only_non_empty: true
  - survey_name: progression
    file: assets/surveys/progression_survey.csv
    format: qualtrics
    machine_header_row_index: 0
    question_text_row_index: 1
    data_start_row_index: 3
    participant_id_column: email
    participant_id_mapping:
      file: assets/surveys/participant_id_map.csv
      key_column: email
      value_column: assigned_participant_id
      normalize: lower
    skip_columns:
      - StartDate
      - EndDate
      - Status
      - IPAddress
      - Progress
      - Duration (in seconds)
      - Finished
      - RecordedDate
      - ResponseId
      - RecipientLastName
      - RecipientFirstName
      - RecipientEmail
      - ExternalReference
      - LocationLatitude
      - LocationLongitude
      - DistributionChannel
      - UserLanguage
    include_only_non_empty: true
  - survey_name: post
    file: assets/surveys/post_survey.csv
    participant_id_column: participant_id
    question_columns: []
